### ISSUE TITLE
issue with n_threads, signs of logFC and type of log

### ISSUE THREAD

**Issue by mihem** [neurorestore/Libra#1]
Congrats to this great package! The function run_de just runs out of the box, great.

There are a few issues, sorry to put them all in one issue.

1) the option n_threads as described in README isn't available:

`DE <- run_de(hagai_toy, n_threads = 8)`
`Error in run_de(hagai_toy, n_threads = 8) : unused argument (n_threads = 8)`

2) How do you know/how can you change which group has positive log fold change? For example in Seurat you determine that with ident.1 and ident.2 and positive values indicate a higher expression in ident.1.

3) Which logFC do you use here? log10 log2 ln?

**Comment by jordansquair** [comment]
Thanks for catching this. 
1. I've pushed a fix for the n_threads (note this is only used in the mixed models)
2. I've added some documentation for logFC to the run_de() function. You can adjust the order by setting the factor levels in your meta data. It will operate the same way as in Seurat (i.e., if level 1 > level 2 the logFC will be positive). 
3. The logFC calculation for single-cell/mixed model methods is identical to that used in Seurat (since the single-cell methods are calculated using FindMarkers. They use log2.). Pseudobulk methods of course calculate it themselves.

I hope this helps.

**Comment by mihem** [comment]
Thanks Jordan for the fast and helpful reply!

1. to make it consistent to the readme it should also be available in the other models (not sure if that's possible with edgeR etc.?) > DE = run_de(hagai_toy, n_threads = 8). Since edgeR is already really fast not sure that is really necessary, and you could maybe just adjust the readme.
2. great
3. cool
4.  in the help of run_de it says "p_val_val": The false discovery rate. You probably mean p_val_adj: adjusted p value by Benjamini Hochberger/false discovery rate?

**Comment by jordansquair** [comment]
1. README is updated for clarification.
3. I will leave it without the specification since other methods use more specific calculations (e.g., DESeq2)
4. Thanks, fixed to indicate BH/FDR.
