### ISSUE TITLE
Error in `group_by()`: Column `cell_type` is not found.

### ISSUE THREAD

**Issue by sshakil12** [neurorestore/Libra#14]
Hello!

When I run run_de() with my own data, I get the error message:

"Error in `group_by()`:
! Must group by variables found in `.data`.
x Column `cell_type` is not found."

The object input is a seurat object and the metadata includes replicate, label, and cell_type columns(approx. 10 replicates, 2 labels, and 1 cell type).  I noticed other people had the same issue/ I would be happy to provide a small sample of my data to figure this out. Thank you.  

Best, 
S.

**Comment by jordansquair** [comment]
if you can provide a small sample of the data that would be great.

**Comment by sshakil12** [comment]
What would be the best way to provide the sample?

**Comment by jordansquair** [comment]
if you can send a link/attachment to my email (see my account page). thanks!

**Comment by sshakil12** [comment]
Just sent it. Thank you!

**Comment by jordansquair** [comment]
So the problem is that your default assay is not set to your scRNAseq data within your Seurat object. Should be careful with this as we don't explicitly call the RNA (since sometimes people name it something else).

`# Test sample data
library(Seurat)
library(Libra)

sc = readRDS("~/Downloads/sample.rds")
DefaultAssay(sc)
[1] "ADT"
de = run_de(sc)
# [1] "macrophages"
# Error: Must group by variables found in `.data`.
# * Column `cell_type` is not found.
# Run `rlang::last_error()` to see where the error occurred.

# fix the default assay
DefaultAssay(sc) = 'RNA'
de = run_de(sc)

# alternatively, you can explicitly provide the correct inputs
expr = GetAssayData(sc, slot = 'counts', assay = 'RNA')
meta = sc@meta.data
de = run_de(expr, meta = meta)
`

**Comment by sshakil12** [comment]
Problem fixed. Once again, thank you!

**Comment by Xicici-Yan** [comment]
Hi, @jordansquair 
I set default assay as 'RNA'. But there is still something wrong with the code.
My seuratobject is like 
![image](https://user-images.githubusercontent.com/112546063/194843077-4cdbc612-8d92-4e18-8c08-5562ec3e502a.png)
When I run 
````
DefaultAssay(seuItg.dft) = 'RNA'

DE = run_de(
  seuItg.dft,
  n_threads = 8
)
````
I got error
![image](https://user-images.githubusercontent.com/112546063/194843859-6be30fdd-fe68-4726-958e-7631acfd5e65.png)

**Comment by jordansquair** [comment]
This is a generic error most likely to do with an issue in your data structure - it is not a bug in libra. I'd be happy to check but please send a subset of your data (e.g., all cells with just 100 genes) to my email. Thanks.

**Comment by Xicici-Yan** [comment]
I have sent test data. Thanks for your kind help.

**Comment by HelloWorldLTY** [comment]
Hi, I addressed this error by setting the cell type column as our desiered in the metadata part, and it seems that we need to make sure that in both HC and diseased cases, we need to include such cell types.
